version: '3.9'

services:
    app:
        restart: unless-stopped
        build: .
        ports:
            - '${PORT}:${PORT}'
        volumes:
            - .:/app
            - /app/node_modules/
        environment:
            - PORT=${PORT}
